agent_name: your_agent
author: elia
version: 0.1.0
description: An agent that fetches and shares motivational quotes.
license: Apache-2.0
aea_version: ">=1.0.0, <2.0.0"
fingerprint:
  abci/README.md: bafybeia5y34dgznojhabsw7js2auxzmwxoubs2yacvscvoqkmt323d3npq
  abci/__init__.py: bafybeicitj573a2sv6dezytno65dxpmhhirwm2jo2vysqj6uui4un7qiti
  abci/abci.proto: bafybeid2kv4fy6xx453apqxashnqfjymhbrvtxj3uq2vdtqr45lvlfjzm4
  abci/abci_pb2.py: bafybeiamdsjnddab32gu3xxa2tj4hkuaor2aboqem5dpt4ug25hhejp2li
  abci/custom_types.py: bafybeihpkluue4c7cunrcaxze3pqexhmwxkybrv4c3bzmkkakze7n6v44a
  abci/dialogues.py: bafybeic4f4vkk7oyaohabshumvca54bqoockfgx3z7cstjk3ubviosk5mm
  abci/message.py: bafybeiegfbh4cslzrqitmqjd437m7wzegez7i5ysmka5ym3icbl4zvgn5y
  abci/serialization.py: bafybeigfsa443dvev6sgcf447ppmqlpkjsd3shwho6mqusvs6bfkt3chsy
  abci/tests/__init__.py: bafybeie4cd5xo7o4teyfjclaju3zoguuahjvkpsbshda3x23jcph53fdpi
  abci/tests/conftest.py: bafybeidomydt6bdji22rndrdb5w773vvdja55o5m5n4pbfslx7ey5euot4
  abci/tests/test_abci.py: bafybeig4gex7e62uxca7riaetmr2pu5xekxg3d7xjvck72zjd3uxny4v64
  abci/tests/test_abci_dialogues.py: bafybeiby6ahpj6dnvjagnyyew3hgncstay37tt3xqu5x2c2yx3nldwvzzi
  abci/tests/test_abci_messages.py: bafybeidbec7g3gvyr4jon57m6pfcobslj3nvnnynzeib3mgvm46d3ywdgi
fingerprint_ignore_patterns: []
private_key_paths: {}
contracts: []
connections:
  - valory/abci:0.1.0:bafybeib5wliqsotle6onwaz63umadnu7lyjeyr2lz6xau2kcq6eirfnh7m
  - valory/p2p_libp2p_client:0.1.0:bafybeihs5zlwa5wlozct3rjlxsirm3ve3e4buse5nfehiky6ymnnfrobne
  - valory/ipfs:0.1.0:bafybeibpcwc673evkpliwp35hmjwjx7obramg2chxityubevnhss3f5cfa
  - valory/ledger:0.19.0:bafybeigntoericenpzvwejqfuc3kqzo2pscs76qoygg5dbj6f4zxusru5e
protocols:
  - open_aea/signing:1.0.0:bafybeihv62fim3wl2bayavfcg3u5e5cxu3b7brtu4cn5xoxd6lqwachasi
  - valory/abci:0.1.0:bafybeiatodhboj6a3p35x4f4b342lzk6ckxpud23awnqbxwjeon3k5y36u
  - valory/acn:1.0.0:bafybeidluaoeakae3exseupaea4i3yvvk5vivyt227xshjlffywwxzcxqe
  - valory/ipfs:0.1.0:bafybeifi2nri7sprmkez4rqzwb4lnu6peoy3bax5k6asf6k5ms7kmjpmkq
  - valory/http:1.0.0:bafybeifugzl63kfdmwrxwphrnrhj7bn6iruxieme3a4ntzejf6kmtuwmae
skills:
  - elia/your_fsm_app_abci:0.1.0:bafybeiehu5piq3x7jlsymprozwu6prg6jumadljvtiohjdbjcn2q4i72dy
  - valory/abstract_abci:0.1.0:bafybeigygqg63cr4sboxz7xfakcfpz55id7ihmj434v5iz3r26t7q6qwie
  - valory/abstract_round_abci:0.1.0:bafybeihyaubqrndsjkrplx4e2tn45jgddt52cxzuhb5iwiznz7qlhrbdbe
  - valory/termination_abci:0.1.0:bafybeifs4vorsmsulzgobr754od2omj6uphylslkrtuadxzludoexld6ny
default_ledger: ethereum
required_ledgers:
  - ethereum
default_connection: valory/abci:0.1.0
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: "[%(asctime)s] [%(levelname)s] %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
        - console
      propagate: true
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.60.0
  open-aea-test-autonomy:
    version: ==0.12.1.post1
---
public_id: elia/your_fsm_app_abci:0.1.0
type: skill
models:
  params:
    args:
      quote_api_url: ${QUOTE_API_URL:str:"https://quotes.rest/qod?category=inspire"}
      wait_time_in_seconds: ${WAIT_TIME:int:86400}
      service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
      share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      use_termination: ${USE_TERMINATION:bool:false}
      use_slashing: ${USE_SLASHING:bool:false}
      slash_cooldown_hours: ${SLASH_COOLDOWN_HOURS:int:0}
      slash_threshold_amount: ${SLASH_THRESHOLD_AMOUNT:int:0}
      light_slash_unit_amount: ${LIGHT_SLASH_UNIT_AMOUNT:int:0}
      serious_slash_unit_amount: ${SERIOUS_SLASH_UNIT_AMOUNT:int:0}
      setup:
        all_participants:
          - "0x0000000000000000000000000000000000000000"
        consensus_threshold: ${CONSENSUS_THRESHOLD:int:3}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:"0x0000000000000000000000000000000000000000"}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_HELLO_WORLD_RPC:str:"http://host.docker.internal:8545"}
      chain_id: ${CHAIN_ID:int:31337}
      poa_chain: ${POA_CHAIN:bool:false}
      default_gas_price_strategy: ${GAS_STRATEGY:str:eip1559}
