name: your_service
author: elia
version: 0.1.0
description: A service that fetches and submits motivational quotes on-chain.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeiaikci6iwrjxkgjvsy4eap4nxfvdueb7h6kv7i6tbfjdwdk5gvpgy
fingerprint_ignore_patterns: []
agent: elia/your_agent:0.1.0:bafybeiagumr3jtcivtfcufkt5m4yx6vubyuwo573h7oqnmzcknbbozglre
number_of_agents: 4
deployment: {}
---
public_id: elia/your_fsm_app_abci:0.1.0
type: skill
models:
  params:
    args:
      quote_api_url: ${QUOTE_API_URL:str:"https://quotes.rest/qod?category=inspire"}
      wait_time_in_seconds: ${WAIT_TIME:int:86400}
      service_registry_address: ${SERVICE_REGISTRY_ADDRESS:str:null}
      share_tm_config_on_startup: ${SHARE_TM_CONFIG_ON_STARTUP:bool:false}
      on_chain_service_id: ${ON_CHAIN_SERVICE_ID:int:null}
      use_termination: ${USE_TERMINATION:bool:false}
      use_slashing: ${USE_SLASHING:bool:false}
      slash_cooldown_hours: ${SLASH_COOLDOWN_HOURS:int:0}
      slash_threshold_amount: ${SLASH_THRESHOLD_AMOUNT:int:0}
      light_slash_unit_amount: ${LIGHT_SLASH_UNIT_AMOUNT:int:0}
      serious_slash_unit_amount: ${SERIOUS_SLASH_UNIT_AMOUNT:int:0}
      setup:
        all_participants:
        - '0x0000000000000000000000000000000000000000'
        consensus_threshold: ${CONSENSUS_THRESHOLD:int:3}
        safe_contract_address: ${SAFE_CONTRACT_ADDRESS:str:"0x0000000000000000000000000000000000000000"}
  benchmark_tool:
    args:
      log_dir: ${LOG_DIR:str:/logs}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${SERVICE_HELLO_WORLD_RPC:str:"http://host.docker.internal:8545"}
      chain_id: ${CHAIN_ID:int:31337}
      poa_chain: ${POA_CHAIN:bool:false}
      default_gas_price_strategy: ${GAS_STRATEGY:str:eip1559}
